Orders don't have a "deactivated" status.
letsencrypt/pebble pull request #301
Opened 2020-02-24 23:21 UTC by jsha

Use "invalid" instead, and add comments linking to the spec.

Fixes #300

2020-02-25 14:31 UTC, cpu commented
:wave: FWIW Boulder has the same divergence: https://github.com/letsencrypt/boulder/blob/9a86abc1550425a73f912c25a11c29160f58a85a/sa/sa.go#L1218-L1221

2020-02-27 00:42 UTC, jvanasco commented
I think I managed to still trigger this. I need to do a few more tests to make sure i'm running the right code - I'm not very good with `go`

2020-02-27 00:59 UTC, jsha commented
Ok, thanks so much for testing! If you need any help, let me know.

2020-02-28 12:35 UTC, Zola-github submitted a review, later dismissed

2020-06-12 20:39 UTC, jvanasco commented
I finally got a chance to test. This works as expected from the RFC.

2022-04-14 22:37 UTC, beautifulentropy commented on core/types.go
> +	// https://tools.ietf.org/html/rfc8555#page-32
```suggestion
	// An order is invalid if ANY of its authzs are invalid, deactivated, or
	// expired per: https://tools.ietf.org/html/rfc8555#page-32
```

2022-04-14 22:39 UTC, beautifulentropy requested changes
Comment nits.

2022-04-14 22:39 UTC, beautifulentropy commented on core/types.go
> +	// Otherwise, an order is pending if **any** of its authzs are pending
```suggestion
	// Otherwise, an order is pending if ANY of its authzs are pending.
```

2022-05-06 23:21 UTC, aarongable approved these changes

2022-05-10 22:21 UTC, beautifulentropy approved these changes

2025-03-07 14:50 UTC, cpu commented
@aarongable @beautifulentropy @mcpherrinm I bumped into this in some client tests and was wondering if one of you could merge this :bow:

2025-03-07 15:36 UTC, jvanasco commented
>  I bumped into this in some client tests and was wondering if one of you could merge this

I now consider this a feature - not a bug - helping me expect/handle broken or malformed responses ;)

2025-03-07 17:26 UTC, aarongable commented
Lol, no idea why this never got merged. While pebble is meant to implement ACME differently than Boulder, it _isn't_ meant to implement ACME _incorrectly_. Thanks for the prod!

2025-03-07 17:27 UTC, merged